- name: "NOTSCORED | 4.1.1.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file"
      line: "max_log_file = 10"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.1

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^admin_space_left_action"
      line: "admin_space_left_action = halt"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.2

- name: "SCORED | 4.1.1.3 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = keep_logs"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.3

- name: "SCORED | 4.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
    - centos7cis_level2 is defined and centos7cis_level2
    - centos7cis_enable_auditd is defined and centos7cis_enable_auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2

- name: "SCORED | 4.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.3

- name: "SCORED | 4.1.4 | PATCH | Ensure events that modify date and time information are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.4

- name: "SCORED | 4.1.5 | PATCH | Ensure events that modify user/group information are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.5

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify the system's network environment are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.6

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.7

- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8

- name: "SCORED | 4.1.9 | PATCH | Ensure session initiation information is collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.9

- name: "SCORED | 4.1.10 | PATCH | Ensure discretionary access control permission modification events are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.10

- name: "SCORED | 4.1.11 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.11

- name: "SCORED | 4.1.12 | PATCH | Ensure use of privileged commands is collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.12

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/audit.rules
      line: "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.14

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /etc/sudoers -p wa -k scope"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/audit.rules
      line: "-w /etc/sudoers -p wa -k scope"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /etc/sudoers.d -p wa -k scope"
      state: present
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.16

- name: "SCORED | 4.1.17 | PATCH | Ensure kernel module loading and unloading is collected"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.17

- name: "SCORED | 4.1.18 | PATCH | Ensure the audit configuration is immutable"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level2 is defined and centos7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.18

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled"
  systemd:
    name: rsyslogd
    enabled: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level2
      - patch
      - rule_4.2.1.1

- name: "NOTSCORED | 4.2.1.2 | PATCH | Ensure logging is configured"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_log_server is defined
    - centos7cis_rsyslog
    - centos7cis_log_server
  tags:
      - level1
      - patch
      - rule_4.2.1.2

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.3

- name: "SCORED | 4.2.1.4 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: "^\\*\\.\\*"
    line: "*.* @@{{ centos7cis_rsyslog_loghost_address }}"
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.4

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | NON-LOG SERVER"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$ModLoad imtcp'
      line: '# $ModLoad imtcp'
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog is defined
    - not centos7cis_log_server
    - centos7cis_rsyslog
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.5

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | NON-LOG SERVER"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$InputTCPServerRun 514'
      line: '# $InputTCPServerRun 514'
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog is defined
    - not centos7cis_log_server
    - centos7cis_rsyslog
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.5

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | LOG SERVER"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$ModLoad imtcp'
      line: '$ModLoad imtcp'
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_log_server is defined
    - centos7cis_rsyslog
    - centos7cis_log_server
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.5

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | LOG SERVER"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$InputTCPServerRun 514'
      line: '$InputTCPServerRun 514'
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_log_server is defined
    - centos7cis_rsyslog
    - centos7cis_log_server
    - rsyslog_installed is defined and rsyslog_installed
  tags:
      - level1
      - patch
      - rule_4.2.1.5

- name: "SCORED | 4.2.2.1 | PATCH | Ensure syslog-ng service is enabled"
  systemd:
    name: syslog-ng
    enabled: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog
    - syslog_ng_installed is defined and syslog_ng_installed
  tags:
      - level1
      - patch
      - rule_4.2.2.1

- name: "NOTSCORED | 4.2.2.2 | PATCH | Ensure logging is configured"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_log_server is defined
    - centos7cis_rsyslog
    - centos7cis_log_server
  tags:
      - level1
      - patch
      - rule_4.2.2.2

- name: "SCORED | 4.2.2.3 | PATCH | Ensure syslog-ng default file permissions configured"
  lineinfile:
    dest: '/etc/syslog-ng/syslog-ng.conf'
    regexp: '^perm(0640);'
    line: '^perm(0640);'
    create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_syslog_ng is defined and centos7cis_log_server is defined
    - centos7cis_syslog_ng
    - centos7cis_log_server
    - syslog_ng_installed is defined and syslog_ng_installed
  tags:
      - level1
      - patch
      - rule_4.2.2.3

- name: "NOTSCORED | 4.2.2.4 | PATCH | Ensure syslog-ng is configured to send logs to a remote log host"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_syslog_ng is defined and centos7cis_log_server is defined
    - centos7cis_syslog_ng
    - centos7cis_log_server
    - syslog_ng_installed is defined and syslog_ng_installed
  tags:
      - level1
      - patch
      - rule_4.2.2.4

- name: "NOTSCORED | 4.2.2.5 | PATCH | Ensure remote syslog-ng messages are only accepted on designated log hosts"
  command: /bin/true
  changed_when: no
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_syslog_ng is defined and centos7cis_log_server is defined
    - centos7cis_syslog_ng
    - centos7cis_log_server
    - syslog_ng_installed is defined and syslog_ng_installed
  tags:
      - level1
      - patch
      - rule_4.2.2.5

- name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
  yum:
    name: rsyslog
    state: present
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_rsyslog is defined and centos7cis_rsyslog
  tags:
      - level1
      - low
      - patch
      - rule_4.2.3

- name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
  yum:
    name: syslog-ng
    state: present
  when:
    - centos7cis_level1 is defined and centos7cis_level1
    - centos7cis_syslog_ng is defined and centos7cis_syslog_ng
  tags:
      - level1
      - low
      - patch
      - rule_4.2.3

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  when:
    - centos7cis_level1 is defined and centos7cis_level1
  tags:
      - level1
      - patch
      - rule_4.2.4

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  lineinfile:
      dest: /etc/logrotate.conf
      regexp: "^#daily"
      line: "daily"
      create: yes
  when:
    - centos7cis_level1 is defined and centos7cis_level1
  tags:
      - level1
      - patch
      - rule_4.3
